version: 2.1

jobs:
  build:
    working_directory: ~/architecture-samples
    steps:
      - checkout
      - run: com.example.android.architecture.blueprints.todoapp.tasks.TaskFragmentTest.java
  test:
    working_directory: ~/architecture-samples
    steps:
      - checkout
      - run: com.example.android.architecture.blueprints.todoapp.tasks.TaskFragmentTest.java

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
